import pandas as pd
import numpy as np

DATA_DIR = '../data'
BETTING_DIR = '.'

def calculate_implied_probability(odds):
    """Convert American Odds to Implied Probability."""
    if pd.isna(odds):
        return np.nan
    if odds < 0:
        return odds / (odds - 100)
    else:
        return 100 / (odds + 100)

def calculate_decimal_odds(odds):
    """Convert American Odds to Decimal Odds."""
    if pd.isna(odds):
        return np.nan
    if odds < 0:
        return 1 + (100 / abs(odds))
    else:
        return 1 + (odds / 100)

def calculate_kelly_fraction(edge, decimal_odds):
    """
    Calculate the Kelly Criterion Bankroll Fraction.
    Formula: Fraction = Edge / (Decimal Odds - 1)
    """
    if pd.isna(edge) or pd.isna(decimal_odds) or decimal_odds <= 1:
        return 0.0
    
    if edge <= 0:
        return 0.0 # Don't bet if no edge
        
    fraction = edge / (decimal_odds - 1)
    return fraction

def process_betting_opportunities():
    print("Loading predictions, odds, and team data...")
    try:
        preds = pd.read_csv(f'{DATA_DIR}/final_submission.csv')
    except FileNotFoundError:
        print(f"Error: {DATA_DIR}/final_submission.csv not found. Please run predict_submission.py first.")
        return
        
    try:
        odds_df = pd.read_csv(f'{DATA_DIR}/sample_odds.csv')
    except FileNotFoundError:
        print(f"Error: {DATA_DIR}/sample_odds.csv not found.")
        return
        
    try:
        teams = pd.read_csv(f'{DATA_DIR}/MTeams.csv')
        team_mapping = dict(zip(teams['TeamID'], teams['TeamName']))
    except FileNotFoundError:
        print(f"Warning: {DATA_DIR}/MTeams.csv not found. Using Team IDs instead of names.")
        team_mapping = {}

    print(f"Loaded {len(preds)} predictions and {len(odds_df)} matches with odds.")
    
    # Process predictions to map them to the odds matchups
    results = []
    
    for idx, row in odds_df.iterrows():
        season = row['Season']
        t1 = row['Team1']
        t2 = row['Team2']
        odds1 = row['Odds1']
        odds2 = row['Odds2']
        
        # Consistent ordering for the ID lookup as generated by predict_submission.py
        # ID is always Year_LowerTeamID_HigherTeamID
        team_lower = min(t1, t2)
        team_higher = max(t1, t2)
        match_id = f"{season}_{team_lower}_{team_higher}"
        
        match_pred = preds[preds['ID'] == match_id]
        if match_pred.empty:
            print(f"Warning: Match {match_id} not found in predictions. Skipping.")
            continue
            
        # The probability in final_submission applies to team_lower beating team_higher
        prob_lower_beats_higher = match_pred.iloc[0]['Pred']
        
        # Determine probability for Team 1 beating Team 2
        if t1 == team_lower:
            model_prob1 = prob_lower_beats_higher
            model_prob2 = 1.0 - prob_lower_beats_higher
        else:
            model_prob1 = 1.0 - prob_lower_beats_higher
            model_prob2 = prob_lower_beats_higher
            
        t1_name = team_mapping.get(t1, f"Team_{t1}")
        t2_name = team_mapping.get(t2, f"Team_{t2}")
        
        # Calculate implied probabilities from odds
        implied_prob1 = calculate_implied_probability(odds1)
        implied_prob2 = calculate_implied_probability(odds2)
        
        # Calculate Edge
        edge1 = model_prob1 - implied_prob1
        edge2 = model_prob2 - implied_prob2
        
        # Calculate Decimal Odds and Kelly Fraction for Team 1
        dec_odds1 = calculate_decimal_odds(odds1)
        kelly1 = calculate_kelly_fraction(edge1, dec_odds1)
        
        # Calculate Decimal Odds and Kelly Fraction for Team 2
        dec_odds2 = calculate_decimal_odds(odds2)
        kelly2 = calculate_kelly_fraction(edge2, dec_odds2)
        
        # Only suggest positive EV bets
        if edge1 > 0:
            results.append({
                'Season': season,
                'Matchup': f"{t1_name} vs {t2_name}",
                'Bet_On': t1_name,
                'Model_Prob': round(model_prob1, 4),
                'Odds': odds1,
                'Implied_Prob': round(implied_prob1, 4),
                'Edge': round(edge1, 4),
                'Kelly_Fraction': round(kelly1, 4),
                'Suggested_Bet_Pct': f"{round(kelly1 * 100 / 4, 2)}%" # Quarter Kelly for safety
            })
            
        if edge2 > 0:
            results.append({
                'Season': season,
                'Matchup': f"{t1_name} vs {t2_name}",
                'Bet_On': t2_name,
                'Model_Prob': round(model_prob2, 4),
                'Odds': odds2,
                'Implied_Prob': round(implied_prob2, 4),
                'Edge': round(edge2, 4),
                'Kelly_Fraction': round(kelly2, 4),
                'Suggested_Bet_Pct': f"{round(kelly2 * 100 / 4, 2)}%" # Quarter Kelly
            })
            
    if not results:
        print("No positive EV bets found.")
        return
        
    results_df = pd.DataFrame(results)
    
    # Sort by Edge (Highest First)
    results_df = results_df.sort_values('Edge', ascending=False)
    
    output_file = 'recommended_bets.csv'
    results_df.to_csv(output_file, index=False)
    print(f"\nFound {len(results_df)} positive EV bets!")
    print(f"Successfully saved recommendations to betting/{output_file}\n")
    print("Top 5 Recommended Bets:")
    print(results_df.head(5).to_string(index=False))

if __name__ == '__main__':
    process_betting_opportunities()
